### ISSUE TITLE
Very interesting, what are the benefits over regular Redux?

### ISSUE THREAD

**Issue by rajaraodv** [zazapeta/rx-react-store#1]
Cool implementation. Can you show some more complex feature or something that shows advantages over simple Redux?

**Comment by zazapeta** [comment]
Hello,

First of all, thx :)

This is good question.

The main advantage is to avoid the use of '[Actions](https://redux.js.org/basics/actions)'.

a la Redux:

```js
// actions.js
const ACTION_ONE = 'ACTION_ONE';
function actionOne(args){
    return {
        type : actionOne,
        args
    };
}


// reducer.js
function reducer(state = {}, action){
    switch(action.type){
        case ACTION_ONE :
            return {
                ...state,
                actionOneDone: true
            };
        default:
            return state;
    }
}

// view.js
dispatch(actionOne('hello'));

```

a la RxStore :

```js
// reducers.js
function actionOne(state, args){ // action type is the function it self
    return {
        ...state,
        actionOneDone: true
    };
}

//view.js
dispatch(actionOne, 'hello');

```

With rxStore, there is no more 'combineRudecer' as we dispatch directly reducers and replace action type by the function it self; no more 'redux-thunk/saga...' as everything is async by default; 

Let me know if it's not clear ^^

Cheers !
